s4:selftest: skip flakey samba4.drs.repl_schema.python for now
UNEXPECTED(error): samba4.drs.repl_schema.python(vampire_dc).repl_schema.DrsReplSchemaTestCase.test_classWithCustomAttribute
REASON: _StringException: _StringException: Content-Type: text/x-traceback;charset=utf8,language=python
traceback
49F
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/testtools/runtest.py", line 128, in _run_user
    return fn(*args)
  File "/usr/lib/python2.6/dist-packages/testtools/testcase.py", line 368, in _run_test_method
    testMethod()
  File "/memdisk/autobuild/flakey/b12973/samba4/source4/torture/drs/python/repl_schema.py", line 179, in test_classWithCustomAttribute
    self._net_drs_replicate(DC=self.dnsname_dc2, fromDC=self.dnsname_dc1, nc_dn=self.schema_dn)
  File "/memdisk/autobuild/flakey/b12973/samba4/source4/torture/drs/python/drs_base.py", line 110, in _net_drs_replicate
    return self.check_output(cmd_line)
  File "bin/python/samba/tests/__init__.py", line 157, in check_output
    raise BlackboxProcessError(retcode, line, p.stdout.read(), p.stderr.read())
BlackboxProcessError: Command '/memdisk/autobuild/flakey/b12973/samba4/bin/samba-tool drs replicate -USAMBADOMAIN/Administrator%locDCpass1 --sync-forced LOCALVAMPIREDC.samba.example.com localdc.samba.example.com CN=Schema,CN=Configuration,DC=samba,DC=example,DC=com'; exit status 255; stdout: ''; stderr: 'ERROR(runtime): DsReplicaSync failed - (-1073741807, 'NT_STATUS_END_OF_FILE')
'
0

As this is an error, we have to skip it instead of adding it to the knowfail file

metze

Autobuild-User: Stefan Metzmacher <metze@samba.org>
Autobuild-Date: Sat Sep 17 08:43:31 CEST 2011 on sn-devel-104