selftest: the tombstone_reanimation test is currently flakey.
See
https://git.samba.org/autobuild.flakey/2015-03-18-0456/samba.stdout

[1657(10627)/1735 at 1h37m36s] samba4.tombstone_reanimation.python(fl2003dc)
Test Container reanimation
UNEXPECTED(failure): samba4.tombstone_reanimation.python.tombstone_reanimation.RestoreContainerObjectTestCase.test_container(fl2003dc)
REASON: Exception: Exception: Traceback (most recent call last):
  File "bin/python/samba/tests/__init__.py", line 113, in run
    testMethod()
  File "/memdisk/autobuild/fl/b2199/samba/source4/dsdb/tests/python/tombstone_reanimation.py", line 541, in test_container
    self.assertAttributesEqual(obj, attr_orig, obj_restore, attr_rest)
  File "/memdisk/autobuild/fl/b2199/samba/source4/dsdb/tests/python/tombstone_reanimation.py", line 86, in assertAttributesEqual
    self.assertEqual(attrs_orig, attrs_rest, "Actual object does not have expected attributes")
AssertionError: Actual object does not have expected attributes

FAILED (1 failures, 0 errors and 0 unexpected successes in 0 testsuites)

There are more occurrences:

https://git.samba.org/autobuild.flakey/2015-03-17-1952/samba.stdout
https://git.samba.org/autobuild.flakey/2015-03-17-1350/samba.stdout
https://git.samba.org/autobuild.flakey/2015-03-16-0452/samba.stdout
https://git.samba.org/autobuild.flakey/2015-03-16-0156/samba.stdout
https://git.samba.org/autobuild.flakey/2015-03-15-1654/samba.stdout
https://git.samba.org/autobuild.flakey/2015-03-14-2253/samba.stdout
https://git.samba.org/autobuild.flakey/2015-03-14-1400/samba.stdout
https://git.samba.org/autobuild.flakey/2015-03-14-0153/samba.stdout
https://git.samba.org/autobuild.flakey/2015-03-13-2251/samba.stdout
https://git.samba.org/autobuild.flakey/2015-03-13-1059/samba.stdout
https://git.samba.org/autobuild.flakey/2015-03-13-0759/samba.stdout

Note that this fails in all environments it is configured to run in.

Signed-off-by: Michael Adam <obnox@samba.org>
Reviewed-by: Stefan Metzmacher <metze@samba.org>