werror: removed WERR_USER_ALREADY_EXISTS (unused, already known as WERR_USER_EXISTS)
Guenther

Signed-off-by: Guenther Deschner <gd@samba.org>
Reviewed-by: Jeremy Allison <jra@samba.org>