buildtools: Restrict dynamic_lookup to macOS
The linker flag probe added by 9938c9a6f7b succeeds on Linux, but
GNU ld.bfd interprets `-undefined,dynamic_lookup` as an undefined
reference to a symbol named "dynamic_lookup". This breaks i686
builds when linking shared libraries that allow undefined symbols.

. . .
[2483/3877] Compiling bin/default/librpc/gen_ndr/py_lsa.c
/usr/bin/ld.bfd: /builddir/build/BUILD/samba-4.25.0-build/samba-4.25.0/
    bin/default/source3/libsamba-cluster-support-private-samba.so:
        undefined reference to `dynamic_lookup'
collect2: error: ld returned 1 exit status
. . .

Only probe and add this macOS specific flag on macOS; Linux
already permits unresolved symbols in these shared libraries
when `-no-undefined` is removed.

BUG: https://bugzilla.samba.org/show_bug.cgi?id=16265

Signed-off-by: Anoop C S <anoopcs@samba.org>
Reviewed-by: Andreas Schneider <asn@samba.org>

Autobuild-User(master): Anoop C S <anoopcs@samba.org>
Autobuild-Date(master): Wed Sep 30 14:38:17 UTC 2026 on atb-devel-224