selftest: mark the samba4.blackbox.dbcheck test as flapping.
This causes frequent autobuild failures recently as follows:

[1730(16550)/1735 at 2h7m43s] samba4.blackbox.dbcheck(ad_dc_ntvfs)
UNEXPECTED(failure): samba4.blackbox.dbcheck(ad_dc_ntvfs).dbcheck(ad_dc_ntvfs:local)
REASON: Exception: Exception: Checking 6799 objects
ERROR: wrong dn[CN=DrsDelObjUser_1426756150,CN=Deleted Objects,DC=samba,DC=example,DC=com] name='DrsDelObjUser_1426756150
DEL:77ec48cb-06cc-4157-a565-770720c30929' new_dn[CN=DrsDelObjUser_1426756150

FAILED (1 failures, 0 errors and 0 unexpected successes in 0 testsuites)

Has been seen flapping since quite some time:

https://git.samba.org/autobuild.flakey/2012-06-22-0340/samba.stdout
https://git.samba.org/autobuild.flakey/2012-06-25-2339/samba.stdout
https://git.samba.org/autobuild.flakey/2012-07-02-1741/samba.stdout
https://git.samba.org/autobuild.flakey/2012-07-31-1344/samba.stdout
https://git.samba.org/autobuild.flakey/2012-09-24-1331/samba.stdout
https://git.samba.org/autobuild.flakey/2012-11-21-0933/samba.stdout
https://git.samba.org/autobuild.flakey/2012-12-02-0140/samba.stdout
https://git.samba.org/autobuild.flakey/2012-12-11-1933/samba.stdout
...
https://git.samba.org/autobuild.flakey/2014-08-20-1715/samba.stdout
https://git.samba.org/autobuild.flakey/2014-09-29-0222/samba.stdout
https://git.samba.org/autobuild.flakey/2014-12-13-1119/samba.stdout
https://git.samba.org/autobuild.flakey/2015-03-19-0529/samba.stdout
https://git.samba.org/autobuild.flakey/2015-03-19-0828/samba.stdout
https://git.samba.org/autobuild.flakey/2015-03-19-1128/samba.stdout

Possibly related to the failure of tombstone_ranimation,
drs.delete_object, and blackbox.samba_tool_demote.

Signed-off-by: Michael Adam <obnox@samba.org>
Reviewed-by: Guenther Deschner <gd@samba.org>

Autobuild-User(master): Michael Adam <obnox@samba.org>
Autobuild-Date(master): Thu Mar 19 20:43:32 CET 2015 on sn-devel-104