subtle bug where files which missed the stat_cache but were added to the cache during the look returned a blank stat struct.  Made weird occurrences such as...
   $ smbclient //pogo/print$
   smb:\ > cd w32x86
     ERROR: Invalid path
   smb:\ > cd w32x86

   smb:\w32x86\ >