Fix bug #6069 - Build breaks with too many arguments to samba-3.3.0/source/smbd/dnsregister.c:85:event_add_timed(). Jeremy. (cherry picked from commit 458a6a4265bc9b429375d7efb52d25969d7faad5)