Revert "autobuild: Return the last 50 log lines"
This reverts commit aab2f39bb7ff330fbb01da4021c096e69a429d2e.

This breaks if log_base is an https url...

Traceback (most recent call last):
  File "script/autobuild.py", line 744, in <module>
    elapsed_time, log_base=options.log_base)
  File "script/autobuild.py", line 608, in email_failure
    f = open("%s/%s.stdout" % (log_base, failed_tag), 'r')
IOError: [Errno 2] No such file or directory:
'https://git.samba.org/uri/samba-autobuild/ctdb.stdout'

Signed-off-by: Stefan Metzmacher <metze@samba.org>
Reviewed-by: Volker Lendecke <vl@samba.org>
Reviewed-by: Ralph Boehme <slow@samba.org>

Autobuild-User(master): Stefan Metzmacher <metze@samba.org>
Autobuild-Date(master): Wed Mar 23 18:59:17 CET 2016 on sn-devel-144