s3:selftest: mark samba3.posix_s3.smb2.lock (dc).rw-exclusive as known to fail
This sometimes fails like this:

[218/271 in 22m22s] samba3.posix_s3.smb2.lock (dc)
UNEXPECTED(failure): samba3.posix_s3.smb2.lock (dc).rw-exclusive
REASON: _StringException: _StringException: ../torture/smb2/lock.c:406: status was NT_STATUS_END_OF_FILE, expected NT_STATUS_OK: (../torture/smb2/lock.c:406)

command: LD_LIBRARY_PATH=/memdisk/tridge/flakey/b18675/source3/source3/bin/shared:/memdisk/tridge/flakey/b18675/source3/source3/bin: bin/smbtorture4 --configfile=$SMB_CONF_PATH --maximum-runtime=1200 --target=samba3 --basedir=/memdisk/tridge/flakey/b18675/source3/source3/st --option="torture:winbindd_netbios_name=$SERVER" --option="torture:winbindd_netbios_domain=$DOMAIN" --option=torture:localdir=/memdisk/tridge/flakey/b18675/source3/source3/st/dc/share --option=torture:sharedelay=100000 //$SERVER_IP/tmp -U$USERNAME%$PASSWORD smb2.lock 2>&1 | ../selftest/filter-subunit --prefix "samba3.posix_s3.smb2.lock (dc)."
expanded command: LD_LIBRARY_PATH=/memdisk/tridge/flakey/b18675/source3/source3/bin/shared:/memdisk/tridge/flakey/b18675/source3/source3/bin: bin/smbtorture4 --configfile=/memdisk/tridge/flakey/b18675/source3/source3/st/client/client.conf --maximum-runtime=1200 --target=samba3 --basedir=/memdisk/tridge/flakey/b18675/source3/source3/st --option="torture:winbindd_netbios_name=LOCALDC2" --option="torture:winbindd_netbios_domain=SAMBA-TEST" --option=torture:localdir=/memdisk/tridge/flakey/b18675/source3/source3/st/dc/share --option=torture:sharedelay=100000 //127.0.0.2/tmp -Utridge%localdc2pass smb2.lock 2>&1 | ../selftest/filter-subunit --prefix "samba3.posix_s3.smb2.lock (dc)."
ERROR: Testsuite[samba3.posix_s3.smb2.lock (dc)]
REASON: Exit code was 1

metze

Autobuild-User: Stefan Metzmacher <metze@samba.org>
Autobuild-Date: Mon Dec 27 12:08:51 CET 2010 on sn-devel-104
(cherry picked from commit e1de884eaa28d8ac67d4060e76e146e0216447ff)