CVE-2021-20254 passdb: Simplify sids_to_unixids()
Best reviewed with "git show -b", there's a "continue" statement that
changes subsequent indentation.

Decouple lookup status of ids from ID_TYPE_NOT_SPECIFIED

Bug: https://bugzilla.samba.org/show_bug.cgi?id=14571

Signed-off-by: Volker Lendecke <vl@samba.org>
Reviewed-by: Jeremy Allison <jra@samba.org>

(backported from patch from master)
[backport by npower@samba.org as master commit
 493f5d6b078e0b0f80d1ef25043e2834cb4fcb87 and
 58e9b62222ad62c81cdf11d704859a227cb2902b creates conflicts
 due to rename of WBC_ID_TYPE_* -> ID_TYPE_*]
[backport by jra@samba.org to work around a compiler
 bug showing this error on gcc 5.6 -> 6.x, seen on
 Debian 9 and Ubuntu 16.04 under -O3:

 ../../source3/passdb/lookup_sid.c:1246:6: error: assuming
 pointer wraparound does not occur when comparing P +- C1
 with P +- C2 [-Werror=strict-overflow]]